# Generated by Django 4.2.7 on 2025-10-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialty',
            field=models.CharField(blank=True, choices=[('heart', 'Heart'), ('skin', 'Skin'), ('children', 'Children'), ('bones_and_joints', 'Bones and Joints'), ('eyes', 'Eyes')], max_length=200, null=True),
        ),
    ]
