# Generated by Django 4.2.7 on 2025-10-25 15:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_user_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='clinic'),
        ),
    ]
