# Generated by Django 4.2.7 on 2025-10-25 15:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='img'),
        ),
    ]
