# Generated by Django 4.2.7 on 2025-10-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reason_for_cancellation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
