# Generated by Django 4.2.7 on 2025-10-25 17:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_appointment_reason_for_cancellation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dtssxxfra/image/upload/v1761411333/default-profile-picture-avatar-user-icon-vector-46389216_y0zwei.avif', max_length=255, null=True, verbose_name='img'),
        ),
    ]
